# Generated by Django 3.1.5 on 2021-03-20 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0011_apply_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='apply',
            name='Website',
        ),
        migrations.AddField(
            model_name='apply',
            name='email',
            field=models.EmailField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apply',
            name='website',
            field=models.URLField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_owner', to='auth.user'),
            preserve_default=False,
        ),
    ]
